use ai_srinidhi_detailsdb;
create table ai_sri_details(SNO INT NOT NULL PRIMARY KEY, NAME VARCHAR(40) NOT NULL,SYSTEM_NUMBER INT NOT NULL,
ERROR VARCHAR(50),OS_NAME VARCHAR(50),RAM VARCHAR(70),PROCESSOR VARCHAR(50),MOUSE_CONDITION VARCHAR(40),KEY_BOARD_CONDITION VARCHAR(40));
select * from ai_sri_details;

insert into ai_sri_details values
(13 ,'Kayalvizhi M  ',1,'visual C++2019 ','Windows 7 Ultimate ','4.00 GB ','INTEL CORE i3 ','Working ', 'working '),
(22 ,'Sangari S  ',2,'Working ','windows 8.1 pro ','2.00 GB ','INTEL Pentium ','working ', 'Working '),
(10 ,'Jayalakshmi R  ',3,'working ','windows 8.1 pro ','4.00 GB ','INTEL CORE i3 ','working ', 'working '),
(5 ,'Fathima M  ',4,'visual C++ 2019 ','windows 7 ultimate  ','2.00GB ','Intel Core  i3 ','working ', 'working '),
(15 ,'LAVANYA M   ',5,'visual C++ 2019 ','Windows 7 Ultimate ','4.00 GB ','Intel Core i3 ','Working ', 'Working '),
(24 ,'Saranya N  ',6,'not supported by this processor type ','Windows 7 Professional ','2.00 GB ','INTEL CORE i3 ','Working ', 'Working '),
(4 ,'Bhavani R  ',8,'working ','windows 10 pro ','4.00 GB ','Intel Core i3 ','working ', 'working '),
(19 ,'Punithavathi D  ',9,'visual C++ 2019 ','windows 8.1 pro ','2.00 GB ','Intel Core 2 Duo ','working ', 'working '),
(26 ,'Snega D  ',10,'working ','windows 10 pro ','4.00 GB ','intel core i3 ','working ', 'working '),
(28 ,'Tamil V  ',11,'visual C++2019 ','windows 8.1 ','4.00 GB ','INTEL CORE i3 ','working ', 'working '),
(27 ,'Srinidhi S  ',12,'visual C++2019 ','windows 8.1 ','2.00 GB ','INTEL CORE i3 ','working ', 'working '),
(23 ,'Santhiya S  ',13,'not supported by this processor type ','windows 10 pro ','4.00 GB ','Intel Core 2 Duo ','working ', 'Working '),
(7 ,'Gnanagowsalya K  ',14,'working ','windows 10 ProN ','8.00 GB ','INTEL CORE i5 ','working ', 'working '),
(11 ,'Jothika J  ',15,'working ','Windows 8.1 Pro ','4.00 GB ','INTEL CORE i3 ','working ', 'working '),
(8 ,'Hajeera Sithika L  ',16,'working ','windows 8.1 ','2GB ','Intel Core 2 Duo ','working ', 'working '),
(6 ,'Ghouse bi S  ',18,'working ','Windows 8.1 Pro ','4GB ','INTEL CORE i3 ',' working ', 'working '),
(29 ,'Vinu Andrews S  ',33,'working ','windows 8.1 ','2gb ','Intel Core 2 Duo ',' working ', 'working '),
(21 ,'Roobankumar  K  ',34,'processor not supported ','windows 7 ultimate ','2.00GB ','intel core 2 duo ','working ', 'working '),
(3 ,'Aysha sithika L  ',17,'WORKING ','windows 10 pro ','2GB ','INTEL CORE i3 ','working ', 'working '),
(18 ,'Priya S  ',23,'not  support by this processer tryp ','windows 7 proffessional ','4.00Gb ','INTEL CORE i3 ','working ', 'working '),
(14 ,'Komaladevi. S  ',7,'visualc++2019 ','Windows 8.1 Pro ','4.00  GB ','Intel Pentium ','Working ', 'Working '),
(12 ,'Kalaiarasan A  ',32,'working ','Windows 8.1 Pro ','4.00 GB ','INTEL CORE i3 ','working ', 'working '),
(1 ,'Abdul Rahman  B  ',42,'working ','windows 8.1 pro ','2 Gb ','Intel Pentium ','working ', 'workimg '),
(2 ,'Arun T  ',43,'working ','windows 8.1 ','2.00GB ','Intel Core 2 Duo ','working ', 'working '),
(17 ,'Prasanth P  ',35,'C++2019 ','Windows 10 Pro ','2.00 GB ','Intel Pentium ','Working ', 'working '),
(30 ,'Yogarajan K  ',36,'Not supported by the processor ','windows 10 pro ','2 GB RAM  ','Intel Pentium ','working ', 'working '),
(25 ,'Saravanan M  ',37,'Working ','Windows 8.1 Pro ','4.00 GB ','INTEL CORE i3 ','Working ', 'Working '),
(9 ,'HARIHARAN A  ',38,'working ','windows 8.1 pro ','4.00 GB ','INTEL CORE i3 ','working ', 'working '),
(20 ,'Raghul S  ',39,'not supported by the processor ','windows 7 ','2.00 GB ','Intel Pentium ','Working ', 'working '),
(16 ,'Narayanan S  ',19,'Working ','windows 8.1 ','4.00GB ','INTEL CORE i3 ','working ', 'working ');
